### PR TITLE
Add pointer authentication registers

### PR DESCRIPTION
**Pull request by usugur**
Pointer Authentication comes with ARMv8.3-A. This commit adds support for reading and writing 128-bit key registers which are referenced in Arm Architecture Reference Manual for A-profile architecture section D13.2 General system control registers.

### CODE REVIEW

**Comment by JaviMerino** [comment]
I have checked these definitions against the Arm Architecture Reference Manual DDI 0487H.a. All good.

**Review by adamgreig — APPROVED** [review]
Thanks for this PR!

We don't currently have any maintainers for this repository, so if anyone is interested in helping to review PRs and cut releases, please comment here or chat to me on Matrix, I'd be happy to get you set up.

**Comment by adamgreig** [comment]
Please could you fix the rustfmt issues?

**Comment by usugur** [comment]
I couldn't see the format difference between the files added in this commit and the existing register files such as (`tpidr_el2.rs`). It seems that `rustfmt` complains about the new line between comments and the `use` keyword. This shouldn't be an issue as all of the register files are using the same format. Can you show that what is missing please?

**Comment by JaviMerino** [comment]
>  Can you show that what is missing please?

This task failed: https://github.com/rust-embedded/aarch64-cpu/actions/runs/4896918903/jobs/8892258745?pr=14

CI must pass for this PR to be merged.

**Comment by usugur** [comment]
The format related issue has been fixed with the latest update. Could you please review and approve to enable the workflow?

**Comment by nchong-at-aws** [comment]
> We don't currently have any maintainers for this repository, so if anyone is interested in helping to review PRs and cut releases, please comment here or chat to me on Matrix, I'd be happy to get you set up.

@adamgreig Hi Adam! I'd be happy to help as a maintainer. I'm familiar with the architecture :)

**Comment by adamgreig** [comment]
@nchong-at-aws great, thank you for volunteering! As the crate is owned by the rust embedded working group, would it be OK for you to join? If you open a PR to https://github.com/rust-embedded/wg#the-cortex-a-team to add your name to the list, I will approve it and you will then get access to this repo and to the crate on crates.io. There's no other responsibility beyond this crate.

**Pull request merged**
